// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myftp.proto

package myftp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UploadStatus int32

const (
	UploadStatus_Unknown UploadStatus = 0
	UploadStatus_Ok      UploadStatus = 1
	UploadStatus_Failed  UploadStatus = 2
)

var UploadStatus_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}

var UploadStatus_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x UploadStatus) String() string {
	return proto.EnumName(UploadStatus_name, int32(x))
}

func (UploadStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07d33c66d3c1a633, []int{0}
}

type UploadRequest struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=FileName,proto3" json:"FileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07d33c66d3c1a633, []int{0}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *UploadRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type UploadResponse struct {
	Message              string       `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Status               UploadStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=myftp.UploadStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07d33c66d3c1a633, []int{1}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UploadResponse) GetStatus() UploadStatus {
	if m != nil {
		return m.Status
	}
	return UploadStatus_Unknown
}

func init() {
	proto.RegisterEnum("myftp.UploadStatus", UploadStatus_name, UploadStatus_value)
	proto.RegisterType((*UploadRequest)(nil), "myftp.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "myftp.UploadResponse")
}

func init() { proto.RegisterFile("myftp.proto", fileDescriptor_07d33c66d3c1a633) }

var fileDescriptor_07d33c66d3c1a633 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x4d, 0xc1, 0xcc, 0xbd, 0xcd, 0x51, 0x9e, 0x0a, 0x65, 0xa7, 0xb1, 0x53, 0x51, 0x98,
	0x30, 0x0f, 0x7e, 0x00, 0x59, 0x6f, 0x2a, 0x64, 0x0c, 0xcf, 0xd1, 0x3d, 0xa5, 0xb4, 0x4d, 0x62,
	0xf3, 0xaa, 0xf8, 0xed, 0xc5, 0xa4, 0x15, 0xdd, 0xf1, 0xf7, 0x4f, 0xf2, 0xcb, 0xff, 0x3d, 0x98,
	0x34, 0x5f, 0xaf, 0xec, 0x56, 0xae, 0xb5, 0x6c, 0xf1, 0x38, 0xc0, 0x72, 0x03, 0xa7, 0x3b, 0x57,
	0x5b, 0xbd, 0x57, 0xf4, 0xde, 0x91, 0x67, 0xcc, 0x60, 0x74, 0x67, 0x0d, 0x93, 0xe1, 0x4c, 0x2c,
	0x44, 0x3e, 0x55, 0x03, 0xe2, 0x1c, 0x4e, 0x8a, 0xb2, 0xa6, 0x07, 0xdd, 0x50, 0x96, 0x2c, 0x44,
	0x3e, 0x56, 0xbf, 0xbc, 0x7c, 0x82, 0xd9, 0xa0, 0xf1, 0xce, 0x1a, 0x4f, 0x3f, 0x9e, 0x7b, 0xf2,
	0x5e, 0xbf, 0x51, 0xf0, 0x8c, 0xd5, 0x80, 0x78, 0x05, 0x72, 0xcb, 0x9a, 0x3b, 0x1f, 0x2c, 0xb3,
	0xf5, 0xd9, 0x2a, 0xf6, 0x8a, 0x82, 0x78, 0xa4, 0xfa, 0x2b, 0x97, 0xd7, 0x30, 0xfd, 0x9b, 0xe3,
	0x04, 0x46, 0x3b, 0x53, 0x19, 0xfb, 0x69, 0xd2, 0x23, 0x94, 0x90, 0x3c, 0x56, 0xa9, 0x40, 0x00,
	0x59, 0xe8, 0xb2, 0xa6, 0x7d, 0x9a, 0xac, 0x37, 0x00, 0x05, 0xbb, 0x2d, 0xb5, 0x1f, 0xe5, 0x0b,
	0xe1, 0x2d, 0xc8, 0xf8, 0x1c, 0xcf, 0xff, 0xfd, 0xd2, 0x4f, 0x3b, 0xbf, 0x38, 0x48, 0x63, 0xf9,
	0x5c, 0x3c, 0xcb, 0xb0, 0xa5, 0x9b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0xaa, 0xc4, 0x3c,
	0x34, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FtpServiceClient is the client API for FtpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FtpServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (FtpService_UploadClient, error)
}

type ftpServiceClient struct {
	cc *grpc.ClientConn
}

func NewFtpServiceClient(cc *grpc.ClientConn) FtpServiceClient {
	return &ftpServiceClient{cc}
}

func (c *ftpServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (FtpService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FtpService_serviceDesc.Streams[0], "/myftp.FtpService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &ftpServiceUploadClient{stream}
	return x, nil
}

type FtpService_UploadClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type ftpServiceUploadClient struct {
	grpc.ClientStream
}

func (x *ftpServiceUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ftpServiceUploadClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FtpServiceServer is the server API for FtpService service.
type FtpServiceServer interface {
	Upload(FtpService_UploadServer) error
}

func RegisterFtpServiceServer(s *grpc.Server, srv FtpServiceServer) {
	s.RegisterService(&_FtpService_serviceDesc, srv)
}

func _FtpService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FtpServiceServer).Upload(&ftpServiceUploadServer{stream})
}

type FtpService_UploadServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type ftpServiceUploadServer struct {
	grpc.ServerStream
}

func (x *ftpServiceUploadServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ftpServiceUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FtpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myftp.FtpService",
	HandlerType: (*FtpServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _FtpService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "myftp.proto",
}
